version: "3"
services:
  oc_cdtapi27:
    build:
      context: ./
      args:
        PYTHON_VERSION: 2.7
        DOCKER_REGISTRY_HOST: ${DOCKER_REGISTRY_HOST}
    image: ${DOCKER_REGISTRY_HOST}/si/corelibs-oc_cdtapi27:${TAG:-master}
  oc_cdtapi37:
    build:
      context: ./
      args:
        PYTHON_VERSION: 3.7
        DOCKER_REGISTRY_HOST: ${DOCKER_REGISTRY_HOST}
    image: ${DOCKER_REGISTRY_HOST}/si/corelibs-oc_cdtapi37:${TAG:-master}
