name: publish-twine
on: [push]
jobs:
  compile-cdtapi3:
    runs-on: ubuntu-latest
    steps:
      - name: Compile
        uses: actions/checkout@v3
      - run: python3 -m pip install --upgrade twine
      - run: python3 setup.py sdist bdist_wheel
      - run: python3 -m pip install dist/*.whl && python3 setup.py test
      - run: echo
      - shell: bash
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: export TWINE_USERNAME="__token__" && export TWINE_PASSWORD && twine upload --verbose dist/*.whl
